# Generated by Django 4.2.3 on 2023-08-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisment', '0003_advertisment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisment',
            name='image',
            field=models.ImageField(default='', upload_to='advertisment/', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
